server.port=8080
server.error.include-exception=true
server.error.include-message=always
server.error.include-stacktrace=always

spring.application.name=noor-backend

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ufzdpvqlvmfnpuldndhv
spring.datasource.password=M@sjidD!&App
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.ebqbxxvoprxchcrcasas
#spring.datasource.password=Wedding@2026&5
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=false

app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47}
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=2592000000

app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000}

app.cloudinary.cloud-name=disjeejix
app.cloudinary.api-key=268616982495515
app.cloudinary.api-secret=6L-GOaEJVhZv9PWBsU_5qDBB_8o

app.firebase.credentials=${FIREBASE_CREDENTIALS_JSON:}
#app.firebase.credentials-file=${FIREBASE_CREDENTIALS_FILE:C:/Users/FT-0006/Downloads/studio-5179544815-8063e-firebase-adminsdk-fbsvc-45e2279ac6.json}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

logging.level.com.noormasjid=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
